# Generated by Django 5.2.12 on 2026-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', 'Migration 0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
